# Generated by Django 4.2.5 on 2023-10-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_buy_price_listing_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='buyer',
        ),
    ]
