# Generated by Django 4.2.5 on 2023-10-14 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_buy_price_remove_listing_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='watchlistings', to=settings.AUTH_USER_MODEL),
        ),
    ]
