# Generated by Django 4.2.5 on 2023-10-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_buy_price_listing_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TimeField(),
        ),
    ]
