# Generated by Django 4.2.5 on 2023-10-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_buy_price_alter_listing_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, default='https://img.freepik.com/free-vector/flat-design-no-photo-sign-design_23-2149288658.jpg?size=338&ext=jpg&ga=GA1.1.1413502914.1697241600&semt=ais', max_length=1000, null=True),
        ),
    ]
