# Generated by Django 4.2.5 on 2023-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, default='https://upload.wikimedia.org/wikipedia/en/thumb/8/85/SVG_Image.svg/480px-SVG_Image.svg.png', max_length=1000, null=True),
        ),
    ]
